#!/bin/sh
# SPDX-License-Identifier: MIT
#
# crossbuild-ko.sh — produce if_agnic.ko WITHOUT a FreeBSD host.
#
# A FreeBSD kernel module is an ET_REL x86-64 ELF object. Compiling all driver
# sources as ONE translation unit with clang targeting x86_64-unknown-freebsd15.1
# yields exactly that, so no ELF linker is needed (macOS ships none). The flags
# mirror sys/conf/kern.mk + kmod.mk for amd64 (releng/15.1); opt_*.h are empty
# as in any out-of-tree module build.
#
# Verify the result with tools/elfsyms.py against the GENERIC kernel of the same
# release before loading it anywhere:
#   tools/elfsyms.py check build/if_agnic.ko /path/to/boot/kernel/kernel
#
# Usage: FREEBSD_SYS=/path/to/freebsd-src/sys tools/crossbuild-ko.sh [outdir]
set -eu
SYS=${FREEBSD_SYS:?set FREEBSD_SYS=/path/to/freebsd-src/sys}
HERE=$(cd "$(dirname "$0")" && pwd)
DRV=$HERE/../driver
OUT=${1:-$HERE/../build}
mkdir -p "$OUT"; OUT=$(cd "$OUT" && pwd)		# absolute: we cd into the objdir below
CC=${CC:-clang}
TARGET=${TARGET:-x86_64-unknown-freebsd15.1}
OBJ=$(mktemp -d "${TMPDIR:-/tmp}/agnic-xbuild.XXXXXX")
mkdir -p "$OUT"; cd "$OBJ"
for m in kern/device_if kern/bus_if dev/pci/pci_if; do
	awk -f "$SYS/tools/makeobjops.awk" "$SYS/$m.m" -h
done
ln -sfn "$SYS/amd64/include" machine; ln -sfn "$SYS/x86/include" x86
for o in global inet inet6 bus ddb kdb ktr hwpmc_hooks sched vm kstack_pages \
    lock_profile printf compat capsicum stack sysctl acpi pci iommu kern_tls \
    ratelimit rss netgraph bpf vlan_var altq sctp ipsec ipfw route mrouting \
    param mac posix random watchdog zstdio geom; do : > "opt_$o.h"; done
cat > agnic_unity.c <<'UNITY'
/* SPDX-License-Identifier: BSD-2-Clause
 * Unity build of if_agnic: one translation unit -> one ET_REL object == the .ko.
 * Generated by tools/crossbuild-ko.sh; do not edit. */
#include "if_agnic.c"
#include "agnic_mgmt.c"
#include "agnic_txrx.c"
#include "agnic_nwa.c"
#include "agnic_pcinet.c"
#include "agnic_pport.c"
UNITY
$CC -target "$TARGET" -c -O2 -pipe -nostdinc \
 -D_KERNEL -DKLD_MODULE -include "$OBJ/opt_global.h" \
 -I"$OBJ" -I"$DRV" -I"$SYS" -I"$SYS/contrib/ck/include" \
 -std=gnu99 -ffreestanding -fno-builtin -fwrapv -fno-common -fno-strict-aliasing \
 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer \
 -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -msoft-float -mno-aes -mno-avx \
 -fno-asynchronous-unwind-tables \
 -ffile-prefix-map="$OBJ"=. -ffile-prefix-map="$DRV"=. -ffile-prefix-map="$SYS"=/usr/src/sys \
 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef \
 -Wno-pointer-sign -Wno-unknown-pragmas -Wno-address-of-packed-member \
 -Wno-format-invalid-specifier -Wno-format-extra-args -Wno-unused-function \
 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types \
 -o "$OUT/if_agnic.ko" agnic_unity.c
cd /; rm -r "$OBJ"
ls -l "$OUT/if_agnic.ko"
echo "built $OUT/if_agnic.ko for $TARGET (unity build; verify with tools/elfsyms.py check)"
